name: Client CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: yarn install & build
      working-directory: ./client
      run: |
        yarn
        yarn build
      env:
        CI: true

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH Commands
        uses: appleboy/ssh-action@v0.0.2
        with:
          host: community.indieco.xyz
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: ./deploy_client.sh
