name: Client CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: yarn install & build
      working-directory: ./client
      run: |
        yarn
        yarn build
      env:
        CI: true
    - name: SSH Deploy
      uses: maddox/actions/ssh@master
      env:
        PRIVATE_KEY: ${{ secrets.KEY }}
        HOST: ${{ secrets.HOST }}
        USER: ${{ secrets.USERNAME }}
      with:
        args: ./deploy_client.sh
